name: homemed
description: "A mobile healthcare platform connecting patients with verified doctors for consultations, prescriptions, and medical advice"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  intl_phone_field: ^3.2.0
  supabase_flutter: ^2.14.1
  flutter_dotenv: ^6.0.1
  pinput: ^6.0.2
  form_builder_validators: ^11.3.0
  date_field: ^6.0.3
  intl: ^0.20.2
  get_storage: ^2.1.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.3
  record: ^7.1.1
  path_provider: ^2.1.6
  skeletonizer: ^2.1.3
  just_audio: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env.local

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
